item_generation_settings:
  max_cap_rare_item_chance: 0.9
  rarity_to_price:
    common: 10
    uncommon: 25
    rare: 60
    epic: 150
    legendary: 400
  default_rarity_weights:
    common: 60
    uncommon: 25
    rare: 10
    epic: 4
    legendary: 1

progression_settings:
  player:
    base_growth: 1.1
  item:
    add_growth: 1.06
    multiply_growth: 1.06
    price_growth: 1.1
  enemy:
    hp_growth: 1.15
    xp_drop_multiplier: 1.1
    boss_price_multiplier: 2
    boss_hp_multiplier: 2
    boss_frequency: 10
    boss_xp_drop_multiplier: 2
  economy:
    gold_growth: 1.05
    price_growth: 1.1
    boss_gold_drop: 3

new_game_settings:
  player:
    xppoints: 0
    gold: 0
    level: 1
    skill_point: 0
    last_time_online: 0
    stats:
      physical_damage: 1
      fire_damage: 1
      ice_damage: 1
      lightning_damage: 1
      emotional_damage: 1
      critical_damage: 0.5
      critical_damage_chance: 0.01
      gold_drop: 1.0
      xp_drop: 1.0
      item_drop: 0.1
      rare_item_chance: 0.05
  active_inventory:
    height: 5
    width: 5
  backpack_inventory:
    height: 5
    width: 5

game_settings:
  language: ru

save_settings:
  save_dir: saves
  save_filename: save.yaml

