item_generation_settings:
  max_cap_rare_item_chance: 0.9
  rarity_to_price:
    common: 10
    uncommon: 25
    rare: 60
    epic: 150
    legendary: 400
  default_rarity_weights:
    common: 60
    uncommon: 25
    rare: 10
    epic: 4
    legendary: 1

progression_settings:
  player:
    base_growth: 1.1
  item:
    add_growth: 1.15
    multiply_growth: 1.05
    price_growth: 1.1
  enemy:
    hp_growth: 1.2
  economy:
    gold_growth: 1.05
    price_growth: 1.1


game_settings:
  language: ru
