ui:
  logo_path: "pyGame/assets/ui/logo.png"
  main_menu_gif_path: "pyGame/assets/ui/main_menu_campfire.gif"
  battle_background_path: "pyGame/assets/ui/cloudless_battle_background.jpg"
  cloud_1_path: "pyGame/assets/ui/cloud_1.png"
  cloud_2_path: "pyGame/assets/ui/cloud_2.png"
  cloud_3_path: "pyGame/assets/ui/cloud_3.png"
  font: "pyGame/assets/font/pixel_font.ttf"
  entities:
    slime:
      idle: "pyGame/assets/ui/Entity/Slime/Idle"
      die: "pyGame/assets/ui/Entity/Slime/Die"
      hit: "pyGame/assets/ui/Entity/Slime/Hit"